# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build-test-check

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'manual build trigger'
      home:
        description: 'location'
        required: false

jobs:
  build-test-and-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        projects: [ TwoPaneLayout, WindowState, ComposeTesting, DragAndDrop ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle packages
        uses: actions/cache@v2
        with:
          path: ${{matrix.projects}}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ${{matrix.projects}}/gradlew

      - name: clean
        run: |
          cd ${{matrix.projects}}
          ./gradlew clean --info
      - name: assemble debug
        run: |
          cd ${{matrix.projects}}
          ./gradlew assembleDebug --info
      - name: unit tests
        run: |
          cd ${{matrix.projects}}
          ./gradlew testDebugUnitTest --info
      - name: lint
        run: |
          cd ${{matrix.projects}}
          ./gradlew lintDebug --info
      - name: ktlint
        run: |
          cd ${{matrix.projects}}
          ./gradlew ktlint --info
